# Generated by Django 4.2.7 on 2023-12-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='characters',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('image', models.ImageField(upload_to='')),
                ('disctions', models.TextField()),
                ('short_description', models.TextField()),
                ('work', models.CharField(max_length=100)),
            ],
        ),
    ]
