# Generated by Django 4.2.7 on 2023-12-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characters',
            old_name='disctions',
            new_name='description',
        ),
    ]
